name: Release
on:
    workflow_dispatch:
    release:
        types:
            - published
jobs:
    register:
        name: Package, Publish, and Register
        runs-on:
            - ubuntu-latest
        steps:
            - id: checkout
              name: Checkout code
              uses: actions/checkout@v4
              
            - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
              name: Login to GitHub Package Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                
            - id: setup-pack
              uses: buildpacks/github-actions/setup-pack@v5.0.0
              
            - id: package
              run: |
                #!/usr/bin/env bash
                set -euo pipefail
                VERSION="$(yq -oy '.buildpack.version' buildpack.toml)"
                pack buildpack package --publish ${REPO}:${VERSION}
              shell: bash
              env:
                REPO: ghcr.io/blocksigner/${{ github.event.repository.name }}
